---
- name: installing httpd package
  yum: name=httpd state=present
- name: copy index.html
  copy: src=index.html dest=/var/www/html
  notify:
      - restart httpd
- name: start httpd service
  service: name=httpd state=started
